name: ci

on:
  push:
    branches:
      'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Log in to YC
        uses: docker/login-action@v1
        with:
          registry: cr.yandex
          username: oauth
          password: AQAAAAA7ko_mAATuwUHBsX_xXUK1kJgGGkFiYUI
      -
         name: Build, tag, and push image to Yandex Cloud Container Registry
         run: |
          docker build -t cr.yandex/crp3e588s9iasinpba77/ubuntu:latest .
          docker push cr.yandex/crp3e588s9iasinpba77/ubuntu:latest
